### ISSUE TITLE
SQL. Fairytales. Task 1

### ISSUE THREAD

**Issue by qw4n7y** [SiKirillo/sandbox#1]
Create a new database, develop SQL table scheme to hold the data about fairytales. Following data should be stored in the database:

- fairytale title and the date of the creation
- authors and their names
- the heros of the fairytales and their name

Please consider the following:

- one fairy tail has single author
- one hero can be an actor of multiple fairytales

Please put your solution in a single text files containing all the SQL required to create all the tables. Put all the SQL required to fill the database with the following data into another file:

1. Shrek. 2001. Author: Adamson. Heros: Shrek, Donkey, Fiona
2. Shrek 2. 2004. Author: Adamson. Heros: Shrek, Donkey, Cat
3. Shrek 3. 2007. Author: Miller. Heros: Shrek, Harold, Cat

**Comment by SiKirillo** [comment]
My done task you can find at sandbox/SQL/fairytalesFromBrother/

**Comment by qw4n7y** [comment]
Well-done! Few comments:
- what's the reason to duplicate table name in the column names? No need to name `name` column in `fairytales` table as `fairytaleName`. KISS
- You've chose to use a join table for `one author - many fairytales` association. In that case (to keep that only one author can be associated to one fairytale) you should add unique index on fairytaleId `column` so the only record for every fairytale could be exists. For now you can add both (authorId = 1, fairytaleId = 1) and (authorId=2, fairytaleId=1) and that would break you scheme (fairytaleId 1 has two authors). For such an association you simple can use `authorId` column added to `fairytales` table. Please investigate

**Comment by qw4n7y** [comment]
One more thing: do not close the issue until your work would be reviewed and approved

**Comment by qw4n7y** [comment]
Done
