### ISSUE TITLE
SQL. Fairytales. Task 2

### ISSUE THREAD

**Issue by qw4n7y** [SiKirillo/sandbox#2]
Write SQL to fetch the following data:

- The very last fairytale
- All fairytales of Adamson author
- All fairytales with Shrek
- All fairytales with Shrek or Harold
- All fairytales without Fiona

**Comment by SiKirillo** [comment]
Hey! New finished task at sandbox/SQL/fairytalesFromBrother/

**Comment by qw4n7y** [comment]
OK. Let's have a look at your queries:

1. `MIN` is a function applied to the grouped set of table rows. Since you are not using `GROUP BY` the result of `SELECT id, date FROM table` would be the same as for `SELECT id, MIN(date) from table`. The task was to fetch the only one record with the minimal `creationDate`. Please have a look at SQL `LIMIT` operator.
2. Your query will be simplified after you add an `authorId` column. Anyway for such queries you should use `INNER JOIN` rather that using `subqueries`
3. Use `JOIN` please
4. Use `JOIN` please
5. Use `JOIN` please

**Comment by qw4n7y** [comment]
Done
