### ISSUE TITLE
SQL. Task 3. Indices

### ISSUE THREAD

**Issue by qw4n7y** [SiKirillo/sandbox#3]
1. Write in comments what are indices in database (no copy paste please). Reveal what data structures indices are based on. Reveal what is unique indices and composite indices.
2. Learn what does `EXPLAIN` SQL command do. Create a table with a single column. Provide explanation of for two queries: first on the table with no indices and seconds for a table with index. Explain the difference in the query execution plans.
3. Add required indices to the `fairytales` database's tables.

**Comment by SiKirillo** [comment]
Hi! I upadate sql-repository!

**Comment by qw4n7y** [comment]
Well-done!
